root = "."
# air在运行时存储临时文件的目录
tmp_dir = "/tmp/air"

[build]
# cmd指令监听当文件有变化时，air需要执行的命令
cmd = "go build -o _output/mb-apiserver -v cmd/mb-apiserver/main.go"

# bin指定执行完cmd命令后，执行的二进制文件
bin = "_output/mb-apiserver"
# args_bin指定了运行二进制文件(bin/full_bin)时添加的额外参数
args_bin = []