// Copyright 2024 alainyan <alainyan@yahoo.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://github.com/Alainyan1/miniblog.

// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package apiserver

import (
	"github.com/onexstack/onexstack/pkg/authz"
	"miniblog/internal/apiserver/biz"
	"miniblog/internal/apiserver/pkg/validation"
	"miniblog/internal/apiserver/store"
	"miniblog/internal/pkg/server"
)

// Injectors from wire.go:

// 使用Wire实现依赖注入逻辑, 为InitializeWebServer函数生成依赖关系图, 自动注入需要的组件, 最终构建出一个完整的server.Server实例
// 参数*Config包含了创建server.Server类型实例的所有依赖项, wire.Build告诉wire如何按照依赖关系注入和构建server.Server对象
func InitializeWebServer(config *Config) (server.Server, error) {
	string2 := config.ServerMode
	db, err := ProvideDB(config)
	if err != nil {
		return nil, err
	}
	datastore := store.NewStore(db)
	v := authz.DefaultOptions()
	authzAuthz, err := authz.NewAuthz(db, v...)
	if err != nil {
		return nil, err
	}
	bizBiz := biz.NewBiz(datastore, authzAuthz)
	validator := validation.New(datastore)
	userRetriever := &UserRetriever{
		store: datastore,
	}
	serverConfig := &ServerConfig{
		cfg:       config,
		biz:       bizBiz,
		val:       validator,
		retriever: userRetriever,
		authz:     authzAuthz,
	}
	serverServer, err := NewWebServer(string2, serverConfig)
	if err != nil {
		return nil, err
	}
	return serverServer, nil
}
